controller_joint_names: ['', 'abad_FR_joint', 'hip_FR_joint', 'knee_FR_joint', 'abad_FL_joint', 'hip_FL_joint', 'knee_FL_joint', 'abad_RR_joint', 'hip_RR_joint', 'knee_RR_joint', 'abad_RL_joint', 'hip_RL_joint', 'knee_RL_joint', ]
